// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ExtendedEntitiesFBS extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static ExtendedEntitiesFBS getRootAsExtendedEntitiesFBS(ByteBuffer _bb) { return getRootAsExtendedEntitiesFBS(_bb, new ExtendedEntitiesFBS()); }
  public static ExtendedEntitiesFBS getRootAsExtendedEntitiesFBS(ByteBuffer _bb, ExtendedEntitiesFBS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ExtendedEntitiesFBS __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MediaEntityFBS media(int j) { return media(new MediaEntityFBS(), j); }
  public MediaEntityFBS media(MediaEntityFBS obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mediaLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public MediaEntityFBS.Vector mediaVector() { return mediaVector(new MediaEntityFBS.Vector()); }
  public MediaEntityFBS.Vector mediaVector(MediaEntityFBS.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createExtendedEntitiesFBS(FlatBufferBuilder builder,
      int mediaOffset) {
    builder.startTable(1);
    ExtendedEntitiesFBS.addMedia(builder, mediaOffset);
    return ExtendedEntitiesFBS.endExtendedEntitiesFBS(builder);
  }

  public static void startExtendedEntitiesFBS(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMedia(FlatBufferBuilder builder, int mediaOffset) { builder.addOffset(0, mediaOffset, 0); }
  public static int createMediaVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMediaVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endExtendedEntitiesFBS(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishExtendedEntitiesFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedExtendedEntitiesFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ExtendedEntitiesFBS get(int j) { return get(new ExtendedEntitiesFBS(), j); }
    public ExtendedEntitiesFBS get(ExtendedEntitiesFBS obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

