// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserFBS extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static UserFBS getRootAsUserFBS(ByteBuffer _bb) { return getRootAsUserFBS(_bb, new UserFBS()); }
  public static UserFBS getRootAsUserFBS(ByteBuffer _bb, UserFBS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserFBS __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, id); return true; } else { return false; } }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String screenName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer screenNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer screenNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String location() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer locationAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer locationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String url() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String description() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public boolean isProtected() { int o = __offset(16); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateIsProtected(boolean isProtected) { int o = __offset(16); if (o != 0) { bb.put(o + bb_pos, (byte)(isProtected ? 1 : 0)); return true; } else { return false; } }
  public boolean verified() { int o = __offset(18); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateVerified(boolean verified) { int o = __offset(18); if (o != 0) { bb.put(o + bb_pos, (byte)(verified ? 1 : 0)); return true; } else { return false; } }
  public int followersCount() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFollowersCount(int followers_count) { int o = __offset(20); if (o != 0) { bb.putInt(o + bb_pos, followers_count); return true; } else { return false; } }
  public int friendsCount() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFriendsCount(int friends_count) { int o = __offset(22); if (o != 0) { bb.putInt(o + bb_pos, friends_count); return true; } else { return false; } }
  public int listedCount() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateListedCount(int listed_count) { int o = __offset(24); if (o != 0) { bb.putInt(o + bb_pos, listed_count); return true; } else { return false; } }
  public int favouritesCount() { int o = __offset(26); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFavouritesCount(int favourites_count) { int o = __offset(26); if (o != 0) { bb.putInt(o + bb_pos, favourites_count); return true; } else { return false; } }
  public int statusesCount() { int o = __offset(28); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateStatusesCount(int statuses_count) { int o = __offset(28); if (o != 0) { bb.putInt(o + bb_pos, statuses_count); return true; } else { return false; } }
  public String createdAt() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer createdAtAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public ByteBuffer createdAtInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 30, 1); }
  public String profileBannerUrl() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBannerUrlAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer profileBannerUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public String profileImageUrlHttps() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileImageUrlHttpsAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer profileImageUrlHttpsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }
  public boolean defaultProfile() { int o = __offset(36); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateDefaultProfile(boolean default_profile) { int o = __offset(36); if (o != 0) { bb.put(o + bb_pos, (byte)(default_profile ? 1 : 0)); return true; } else { return false; } }
  public String withheldInCountries(int j) { int o = __offset(38); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int withheldInCountriesLength() { int o = __offset(38); return o != 0 ? __vector_len(o) : 0; }
  public StringVector withheldInCountriesVector() { return withheldInCountriesVector(new StringVector()); }
  public StringVector withheldInCountriesVector(StringVector obj) { int o = __offset(38); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String withheldScope() { int o = __offset(40); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer withheldScopeAsByteBuffer() { return __vector_as_bytebuffer(40, 1); }
  public ByteBuffer withheldScopeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 40, 1); }
  public URLEntityFBS descriptionURLEntities(int j) { return descriptionURLEntities(new URLEntityFBS(), j); }
  public URLEntityFBS descriptionURLEntities(URLEntityFBS obj, int j) { int o = __offset(42); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int descriptionURLEntitiesLength() { int o = __offset(42); return o != 0 ? __vector_len(o) : 0; }
  public URLEntityFBS.Vector descriptionURLEntitiesVector() { return descriptionURLEntitiesVector(new URLEntityFBS.Vector()); }
  public URLEntityFBS.Vector descriptionURLEntitiesVector(URLEntityFBS.Vector obj) { int o = __offset(42); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean geoEnabled() { int o = __offset(44); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateGeoEnabled(boolean geo_enabled) { int o = __offset(44); if (o != 0) { bb.put(o + bb_pos, (byte)(geo_enabled ? 1 : 0)); return true; } else { return false; } }
  public String lang() { int o = __offset(46); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer langAsByteBuffer() { return __vector_as_bytebuffer(46, 1); }
  public ByteBuffer langInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 46, 1); }
  public boolean contributorsEnabled() { int o = __offset(48); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateContributorsEnabled(boolean contributors_enabled) { int o = __offset(48); if (o != 0) { bb.put(o + bb_pos, (byte)(contributors_enabled ? 1 : 0)); return true; } else { return false; } }
  public String profileBackgroundColor() { int o = __offset(50); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundColorAsByteBuffer() { return __vector_as_bytebuffer(50, 1); }
  public ByteBuffer profileBackgroundColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 50, 1); }
  public String profileBackgroundImageUrl() { int o = __offset(52); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundImageUrlAsByteBuffer() { return __vector_as_bytebuffer(52, 1); }
  public ByteBuffer profileBackgroundImageUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 52, 1); }
  public String profileBackgroundImageUrlHttps() { int o = __offset(54); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundImageUrlHttpsAsByteBuffer() { return __vector_as_bytebuffer(54, 1); }
  public ByteBuffer profileBackgroundImageUrlHttpsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 54, 1); }
  public boolean profileBackgroundTile() { int o = __offset(56); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateProfileBackgroundTile(boolean profile_background_tile) { int o = __offset(56); if (o != 0) { bb.put(o + bb_pos, (byte)(profile_background_tile ? 1 : 0)); return true; } else { return false; } }
  public String profileImageUrl() { int o = __offset(58); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileImageUrlAsByteBuffer() { return __vector_as_bytebuffer(58, 1); }
  public ByteBuffer profileImageUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 58, 1); }
  public String profileLinkColor() { int o = __offset(60); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileLinkColorAsByteBuffer() { return __vector_as_bytebuffer(60, 1); }
  public ByteBuffer profileLinkColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 60, 1); }
  public String profileSidebarBorderColor() { int o = __offset(62); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileSidebarBorderColorAsByteBuffer() { return __vector_as_bytebuffer(62, 1); }
  public ByteBuffer profileSidebarBorderColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 62, 1); }
  public String profileSidebarFillColor() { int o = __offset(64); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileSidebarFillColorAsByteBuffer() { return __vector_as_bytebuffer(64, 1); }
  public ByteBuffer profileSidebarFillColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 64, 1); }
  public String profileTextColor() { int o = __offset(66); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileTextColorAsByteBuffer() { return __vector_as_bytebuffer(66, 1); }
  public ByteBuffer profileTextColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 66, 1); }
  public boolean profileUseBackgroundImage() { int o = __offset(68); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateProfileUseBackgroundImage(boolean profile_use_background_image) { int o = __offset(68); if (o != 0) { bb.put(o + bb_pos, (byte)(profile_use_background_image ? 1 : 0)); return true; } else { return false; } }
  public int utcOffset() { int o = __offset(70); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateUtcOffset(int utc_offset) { int o = __offset(70); if (o != 0) { bb.putInt(o + bb_pos, utc_offset); return true; } else { return false; } }
  public String timeZone() { int o = __offset(72); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer timeZoneAsByteBuffer() { return __vector_as_bytebuffer(72, 1); }
  public ByteBuffer timeZoneInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 72, 1); }
  public boolean isTranslator() { int o = __offset(74); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateIsTranslator(boolean is_translator) { int o = __offset(74); if (o != 0) { bb.put(o + bb_pos, (byte)(is_translator ? 1 : 0)); return true; } else { return false; } }
  public boolean followRequestSent() { int o = __offset(76); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateFollowRequestSent(boolean follow_request_sent) { int o = __offset(76); if (o != 0) { bb.put(o + bb_pos, (byte)(follow_request_sent ? 1 : 0)); return true; } else { return false; } }
  public boolean showAllInlineMedia() { int o = __offset(78); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateShowAllInlineMedia(boolean showAllInlineMedia) { int o = __offset(78); if (o != 0) { bb.put(o + bb_pos, (byte)(showAllInlineMedia ? 1 : 0)); return true; } else { return false; } }

  public static int createUserFBS(FlatBufferBuilder builder,
      long id,
      int nameOffset,
      int screen_nameOffset,
      int locationOffset,
      int urlOffset,
      int descriptionOffset,
      boolean isProtected,
      boolean verified,
      int followers_count,
      int friends_count,
      int listed_count,
      int favourites_count,
      int statuses_count,
      int created_atOffset,
      int profile_banner_urlOffset,
      int profile_image_url_httpsOffset,
      boolean default_profile,
      int withheld_in_countriesOffset,
      int withheld_scopeOffset,
      int descriptionURLEntitiesOffset,
      boolean geo_enabled,
      int langOffset,
      boolean contributors_enabled,
      int profile_background_colorOffset,
      int profile_background_image_urlOffset,
      int profile_background_image_url_httpsOffset,
      boolean profile_background_tile,
      int profile_image_urlOffset,
      int profile_link_colorOffset,
      int profile_sidebar_border_colorOffset,
      int profile_sidebar_fill_colorOffset,
      int profile_text_colorOffset,
      boolean profile_use_background_image,
      int utc_offset,
      int time_zoneOffset,
      boolean is_translator,
      boolean follow_request_sent,
      boolean showAllInlineMedia) {
    builder.startTable(38);
    UserFBS.addId(builder, id);
    UserFBS.addTimeZone(builder, time_zoneOffset);
    UserFBS.addUtcOffset(builder, utc_offset);
    UserFBS.addProfileTextColor(builder, profile_text_colorOffset);
    UserFBS.addProfileSidebarFillColor(builder, profile_sidebar_fill_colorOffset);
    UserFBS.addProfileSidebarBorderColor(builder, profile_sidebar_border_colorOffset);
    UserFBS.addProfileLinkColor(builder, profile_link_colorOffset);
    UserFBS.addProfileImageUrl(builder, profile_image_urlOffset);
    UserFBS.addProfileBackgroundImageUrlHttps(builder, profile_background_image_url_httpsOffset);
    UserFBS.addProfileBackgroundImageUrl(builder, profile_background_image_urlOffset);
    UserFBS.addProfileBackgroundColor(builder, profile_background_colorOffset);
    UserFBS.addLang(builder, langOffset);
    UserFBS.addDescriptionURLEntities(builder, descriptionURLEntitiesOffset);
    UserFBS.addWithheldScope(builder, withheld_scopeOffset);
    UserFBS.addWithheldInCountries(builder, withheld_in_countriesOffset);
    UserFBS.addProfileImageUrlHttps(builder, profile_image_url_httpsOffset);
    UserFBS.addProfileBannerUrl(builder, profile_banner_urlOffset);
    UserFBS.addCreatedAt(builder, created_atOffset);
    UserFBS.addStatusesCount(builder, statuses_count);
    UserFBS.addFavouritesCount(builder, favourites_count);
    UserFBS.addListedCount(builder, listed_count);
    UserFBS.addFriendsCount(builder, friends_count);
    UserFBS.addFollowersCount(builder, followers_count);
    UserFBS.addDescription(builder, descriptionOffset);
    UserFBS.addUrl(builder, urlOffset);
    UserFBS.addLocation(builder, locationOffset);
    UserFBS.addScreenName(builder, screen_nameOffset);
    UserFBS.addName(builder, nameOffset);
    UserFBS.addShowAllInlineMedia(builder, showAllInlineMedia);
    UserFBS.addFollowRequestSent(builder, follow_request_sent);
    UserFBS.addIsTranslator(builder, is_translator);
    UserFBS.addProfileUseBackgroundImage(builder, profile_use_background_image);
    UserFBS.addProfileBackgroundTile(builder, profile_background_tile);
    UserFBS.addContributorsEnabled(builder, contributors_enabled);
    UserFBS.addGeoEnabled(builder, geo_enabled);
    UserFBS.addDefaultProfile(builder, default_profile);
    UserFBS.addVerified(builder, verified);
    UserFBS.addIsProtected(builder, isProtected);
    return UserFBS.endUserFBS(builder);
  }

  public static void startUserFBS(FlatBufferBuilder builder) { builder.startTable(38); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addScreenName(FlatBufferBuilder builder, int screenNameOffset) { builder.addOffset(2, screenNameOffset, 0); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addOffset(3, locationOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(4, urlOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(5, descriptionOffset, 0); }
  public static void addIsProtected(FlatBufferBuilder builder, boolean isProtected) { builder.addBoolean(6, isProtected, false); }
  public static void addVerified(FlatBufferBuilder builder, boolean verified) { builder.addBoolean(7, verified, false); }
  public static void addFollowersCount(FlatBufferBuilder builder, int followersCount) { builder.addInt(8, followersCount, 0); }
  public static void addFriendsCount(FlatBufferBuilder builder, int friendsCount) { builder.addInt(9, friendsCount, 0); }
  public static void addListedCount(FlatBufferBuilder builder, int listedCount) { builder.addInt(10, listedCount, 0); }
  public static void addFavouritesCount(FlatBufferBuilder builder, int favouritesCount) { builder.addInt(11, favouritesCount, 0); }
  public static void addStatusesCount(FlatBufferBuilder builder, int statusesCount) { builder.addInt(12, statusesCount, 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, int createdAtOffset) { builder.addOffset(13, createdAtOffset, 0); }
  public static void addProfileBannerUrl(FlatBufferBuilder builder, int profileBannerUrlOffset) { builder.addOffset(14, profileBannerUrlOffset, 0); }
  public static void addProfileImageUrlHttps(FlatBufferBuilder builder, int profileImageUrlHttpsOffset) { builder.addOffset(15, profileImageUrlHttpsOffset, 0); }
  public static void addDefaultProfile(FlatBufferBuilder builder, boolean defaultProfile) { builder.addBoolean(16, defaultProfile, false); }
  public static void addWithheldInCountries(FlatBufferBuilder builder, int withheldInCountriesOffset) { builder.addOffset(17, withheldInCountriesOffset, 0); }
  public static int createWithheldInCountriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startWithheldInCountriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addWithheldScope(FlatBufferBuilder builder, int withheldScopeOffset) { builder.addOffset(18, withheldScopeOffset, 0); }
  public static void addDescriptionURLEntities(FlatBufferBuilder builder, int descriptionURLEntitiesOffset) { builder.addOffset(19, descriptionURLEntitiesOffset, 0); }
  public static int createDescriptionURLEntitiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDescriptionURLEntitiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGeoEnabled(FlatBufferBuilder builder, boolean geoEnabled) { builder.addBoolean(20, geoEnabled, false); }
  public static void addLang(FlatBufferBuilder builder, int langOffset) { builder.addOffset(21, langOffset, 0); }
  public static void addContributorsEnabled(FlatBufferBuilder builder, boolean contributorsEnabled) { builder.addBoolean(22, contributorsEnabled, false); }
  public static void addProfileBackgroundColor(FlatBufferBuilder builder, int profileBackgroundColorOffset) { builder.addOffset(23, profileBackgroundColorOffset, 0); }
  public static void addProfileBackgroundImageUrl(FlatBufferBuilder builder, int profileBackgroundImageUrlOffset) { builder.addOffset(24, profileBackgroundImageUrlOffset, 0); }
  public static void addProfileBackgroundImageUrlHttps(FlatBufferBuilder builder, int profileBackgroundImageUrlHttpsOffset) { builder.addOffset(25, profileBackgroundImageUrlHttpsOffset, 0); }
  public static void addProfileBackgroundTile(FlatBufferBuilder builder, boolean profileBackgroundTile) { builder.addBoolean(26, profileBackgroundTile, false); }
  public static void addProfileImageUrl(FlatBufferBuilder builder, int profileImageUrlOffset) { builder.addOffset(27, profileImageUrlOffset, 0); }
  public static void addProfileLinkColor(FlatBufferBuilder builder, int profileLinkColorOffset) { builder.addOffset(28, profileLinkColorOffset, 0); }
  public static void addProfileSidebarBorderColor(FlatBufferBuilder builder, int profileSidebarBorderColorOffset) { builder.addOffset(29, profileSidebarBorderColorOffset, 0); }
  public static void addProfileSidebarFillColor(FlatBufferBuilder builder, int profileSidebarFillColorOffset) { builder.addOffset(30, profileSidebarFillColorOffset, 0); }
  public static void addProfileTextColor(FlatBufferBuilder builder, int profileTextColorOffset) { builder.addOffset(31, profileTextColorOffset, 0); }
  public static void addProfileUseBackgroundImage(FlatBufferBuilder builder, boolean profileUseBackgroundImage) { builder.addBoolean(32, profileUseBackgroundImage, false); }
  public static void addUtcOffset(FlatBufferBuilder builder, int utcOffset) { builder.addInt(33, utcOffset, 0); }
  public static void addTimeZone(FlatBufferBuilder builder, int timeZoneOffset) { builder.addOffset(34, timeZoneOffset, 0); }
  public static void addIsTranslator(FlatBufferBuilder builder, boolean isTranslator) { builder.addBoolean(35, isTranslator, false); }
  public static void addFollowRequestSent(FlatBufferBuilder builder, boolean followRequestSent) { builder.addBoolean(36, followRequestSent, false); }
  public static void addShowAllInlineMedia(FlatBufferBuilder builder, boolean showAllInlineMedia) { builder.addBoolean(37, showAllInlineMedia, false); }
  public static int endUserFBS(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishUserFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedUserFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserFBS get(int j) { return get(new UserFBS(), j); }
    public UserFBS get(UserFBS obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

