// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MapStringBool extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static MapStringBool getRootAsMapStringBool(ByteBuffer _bb) { return getRootAsMapStringBool(_bb, new MapStringBool()); }
  public static MapStringBool getRootAsMapStringBool(ByteBuffer _bb, MapStringBool obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MapStringBool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer keyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean value() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateValue(boolean value) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)(value ? 1 : 0)); return true; } else { return false; } }

  public static int createMapStringBool(FlatBufferBuilder builder,
      int keyOffset,
      boolean value) {
    builder.startTable(2);
    MapStringBool.addKey(builder, keyOffset);
    MapStringBool.addValue(builder, value);
    return MapStringBool.endMapStringBool(builder);
  }

  public static void startMapStringBool(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, boolean value) { builder.addBoolean(1, value, false); }
  public static int endMapStringBool(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MapStringBool get(int j) { return get(new MapStringBool(), j); }
    public MapStringBool get(MapStringBool obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

