// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BoundingBoxCoordinateFBS extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static BoundingBoxCoordinateFBS getRootAsBoundingBoxCoordinateFBS(ByteBuffer _bb) { return getRootAsBoundingBoxCoordinateFBS(_bb, new BoundingBoxCoordinateFBS()); }
  public static BoundingBoxCoordinateFBS getRootAsBoundingBoxCoordinateFBS(ByteBuffer _bb, BoundingBoxCoordinateFBS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BoundingBoxCoordinateFBS __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String type() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public at.tugraz.tweet.flatbuffers.DoubleList1 coordinates(int j) { return coordinates(new at.tugraz.tweet.flatbuffers.DoubleList1(), j); }
  public at.tugraz.tweet.flatbuffers.DoubleList1 coordinates(at.tugraz.tweet.flatbuffers.DoubleList1 obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int coordinatesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public at.tugraz.tweet.flatbuffers.DoubleList1.Vector coordinatesVector() { return coordinatesVector(new at.tugraz.tweet.flatbuffers.DoubleList1.Vector()); }
  public at.tugraz.tweet.flatbuffers.DoubleList1.Vector coordinatesVector(at.tugraz.tweet.flatbuffers.DoubleList1.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createBoundingBoxCoordinateFBS(FlatBufferBuilder builder,
      int typeOffset,
      int coordinatesOffset) {
    builder.startTable(2);
    BoundingBoxCoordinateFBS.addCoordinates(builder, coordinatesOffset);
    BoundingBoxCoordinateFBS.addType(builder, typeOffset);
    return BoundingBoxCoordinateFBS.endBoundingBoxCoordinateFBS(builder);
  }

  public static void startBoundingBoxCoordinateFBS(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(0, typeOffset, 0); }
  public static void addCoordinates(FlatBufferBuilder builder, int coordinatesOffset) { builder.addOffset(1, coordinatesOffset, 0); }
  public static int createCoordinatesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBoundingBoxCoordinateFBS(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBoundingBoxCoordinateFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBoundingBoxCoordinateFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BoundingBoxCoordinateFBS get(int j) { return get(new BoundingBoxCoordinateFBS(), j); }
    public BoundingBoxCoordinateFBS get(BoundingBoxCoordinateFBS obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

