// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserMentionEntityFBS extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static UserMentionEntityFBS getRootAsUserMentionEntityFBS(ByteBuffer _bb) { return getRootAsUserMentionEntityFBS(_bb, new UserMentionEntityFBS()); }
  public static UserMentionEntityFBS getRootAsUserMentionEntityFBS(ByteBuffer _bb, UserMentionEntityFBS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserMentionEntityFBS __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, id); return true; } else { return false; } }
  public String idStr() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idStrAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer idStrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int indices(int j) { int o = __offset(8); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int indicesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public IntVector indicesVector() { return indicesVector(new IntVector()); }
  public IntVector indicesVector(IntVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer indicesAsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer indicesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }
  public boolean mutateIndices(int j, int indices) { int o = __offset(8); if (o != 0) { bb.putInt(__vector(o) + j * 4, indices); return true; } else { return false; } }
  public String name() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String screenName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer screenNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer screenNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createUserMentionEntityFBS(FlatBufferBuilder builder,
      long id,
      int id_strOffset,
      int indicesOffset,
      int nameOffset,
      int screen_nameOffset) {
    builder.startTable(5);
    UserMentionEntityFBS.addId(builder, id);
    UserMentionEntityFBS.addScreenName(builder, screen_nameOffset);
    UserMentionEntityFBS.addName(builder, nameOffset);
    UserMentionEntityFBS.addIndices(builder, indicesOffset);
    UserMentionEntityFBS.addIdStr(builder, id_strOffset);
    return UserMentionEntityFBS.endUserMentionEntityFBS(builder);
  }

  public static void startUserMentionEntityFBS(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addIdStr(FlatBufferBuilder builder, int idStrOffset) { builder.addOffset(1, idStrOffset, 0); }
  public static void addIndices(FlatBufferBuilder builder, int indicesOffset) { builder.addOffset(2, indicesOffset, 0); }
  public static int createIndicesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startIndicesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(3, nameOffset, 0); }
  public static void addScreenName(FlatBufferBuilder builder, int screenNameOffset) { builder.addOffset(4, screenNameOffset, 0); }
  public static int endUserMentionEntityFBS(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishUserMentionEntityFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedUserMentionEntityFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserMentionEntityFBS get(int j) { return get(new UserMentionEntityFBS(), j); }
    public UserMentionEntityFBS get(UserMentionEntityFBS obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

