// automatically generated by the FlatBuffers compiler, do not modify

package at.tugraz.tweet.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserFBS extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static UserFBS getRootAsUserFBS(ByteBuffer _bb) { return getRootAsUserFBS(_bb, new UserFBS()); }
  public static UserFBS getRootAsUserFBS(ByteBuffer _bb, UserFBS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserFBS __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, id); return true; } else { return false; } }
  public String idStr() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idStrAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer idStrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String screenName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer screenNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer screenNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String location() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer locationAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer locationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String url() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String description() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public boolean isProtected() { int o = __offset(18); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateIsProtected(boolean is_protected) { int o = __offset(18); if (o != 0) { bb.put(o + bb_pos, (byte)(is_protected ? 1 : 0)); return true; } else { return false; } }
  public boolean verified() { int o = __offset(20); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateVerified(boolean verified) { int o = __offset(20); if (o != 0) { bb.put(o + bb_pos, (byte)(verified ? 1 : 0)); return true; } else { return false; } }
  public int followersCount() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFollowersCount(int followers_count) { int o = __offset(22); if (o != 0) { bb.putInt(o + bb_pos, followers_count); return true; } else { return false; } }
  public int friendsCount() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFriendsCount(int friends_count) { int o = __offset(24); if (o != 0) { bb.putInt(o + bb_pos, friends_count); return true; } else { return false; } }
  public int listedCount() { int o = __offset(26); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateListedCount(int listed_count) { int o = __offset(26); if (o != 0) { bb.putInt(o + bb_pos, listed_count); return true; } else { return false; } }
  public int favouritesCount() { int o = __offset(28); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateFavouritesCount(int favourites_count) { int o = __offset(28); if (o != 0) { bb.putInt(o + bb_pos, favourites_count); return true; } else { return false; } }
  public int statusesCount() { int o = __offset(30); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateStatusesCount(int statuses_count) { int o = __offset(30); if (o != 0) { bb.putInt(o + bb_pos, statuses_count); return true; } else { return false; } }
  public String createdAt() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer createdAtAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer createdAtInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public String profileBannerUrl() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBannerUrlAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer profileBannerUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }
  public String profileImageUrlHttps() { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileImageUrlHttpsAsByteBuffer() { return __vector_as_bytebuffer(36, 1); }
  public ByteBuffer profileImageUrlHttpsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 36, 1); }
  public boolean defaultProfile() { int o = __offset(38); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateDefaultProfile(boolean default_profile) { int o = __offset(38); if (o != 0) { bb.put(o + bb_pos, (byte)(default_profile ? 1 : 0)); return true; } else { return false; } }
  public String withheldInCountries(int j) { int o = __offset(40); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int withheldInCountriesLength() { int o = __offset(40); return o != 0 ? __vector_len(o) : 0; }
  public StringVector withheldInCountriesVector() { return withheldInCountriesVector(new StringVector()); }
  public StringVector withheldInCountriesVector(StringVector obj) { int o = __offset(40); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String withheldScope() { int o = __offset(42); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer withheldScopeAsByteBuffer() { return __vector_as_bytebuffer(42, 1); }
  public ByteBuffer withheldScopeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 42, 1); }
  public at.tugraz.tweet.flatbuffers.URLEntityFBS descriptionUrlEntities(int j) { return descriptionUrlEntities(new at.tugraz.tweet.flatbuffers.URLEntityFBS(), j); }
  public at.tugraz.tweet.flatbuffers.URLEntityFBS descriptionUrlEntities(at.tugraz.tweet.flatbuffers.URLEntityFBS obj, int j) { int o = __offset(44); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int descriptionUrlEntitiesLength() { int o = __offset(44); return o != 0 ? __vector_len(o) : 0; }
  public at.tugraz.tweet.flatbuffers.URLEntityFBS.Vector descriptionUrlEntitiesVector() { return descriptionUrlEntitiesVector(new at.tugraz.tweet.flatbuffers.URLEntityFBS.Vector()); }
  public at.tugraz.tweet.flatbuffers.URLEntityFBS.Vector descriptionUrlEntitiesVector(at.tugraz.tweet.flatbuffers.URLEntityFBS.Vector obj) { int o = __offset(44); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean geoEnabled() { int o = __offset(46); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateGeoEnabled(boolean geo_enabled) { int o = __offset(46); if (o != 0) { bb.put(o + bb_pos, (byte)(geo_enabled ? 1 : 0)); return true; } else { return false; } }
  public String lang() { int o = __offset(48); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer langAsByteBuffer() { return __vector_as_bytebuffer(48, 1); }
  public ByteBuffer langInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 48, 1); }
  public boolean contributorsEnabled() { int o = __offset(50); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateContributorsEnabled(boolean contributors_enabled) { int o = __offset(50); if (o != 0) { bb.put(o + bb_pos, (byte)(contributors_enabled ? 1 : 0)); return true; } else { return false; } }
  public String profileBackgroundColor() { int o = __offset(52); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundColorAsByteBuffer() { return __vector_as_bytebuffer(52, 1); }
  public ByteBuffer profileBackgroundColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 52, 1); }
  public String profileBackgroundImageUrl() { int o = __offset(54); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundImageUrlAsByteBuffer() { return __vector_as_bytebuffer(54, 1); }
  public ByteBuffer profileBackgroundImageUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 54, 1); }
  public String profileBackgroundImageUrlHttps() { int o = __offset(56); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileBackgroundImageUrlHttpsAsByteBuffer() { return __vector_as_bytebuffer(56, 1); }
  public ByteBuffer profileBackgroundImageUrlHttpsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 56, 1); }
  public boolean profileBackgroundTile() { int o = __offset(58); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateProfileBackgroundTile(boolean profile_background_tile) { int o = __offset(58); if (o != 0) { bb.put(o + bb_pos, (byte)(profile_background_tile ? 1 : 0)); return true; } else { return false; } }
  public String profileImageUrl() { int o = __offset(60); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileImageUrlAsByteBuffer() { return __vector_as_bytebuffer(60, 1); }
  public ByteBuffer profileImageUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 60, 1); }
  public String profileLinkColor() { int o = __offset(62); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileLinkColorAsByteBuffer() { return __vector_as_bytebuffer(62, 1); }
  public ByteBuffer profileLinkColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 62, 1); }
  public String profileSidebarBorderColor() { int o = __offset(64); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileSidebarBorderColorAsByteBuffer() { return __vector_as_bytebuffer(64, 1); }
  public ByteBuffer profileSidebarBorderColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 64, 1); }
  public String profileSidebarFillColor() { int o = __offset(66); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileSidebarFillColorAsByteBuffer() { return __vector_as_bytebuffer(66, 1); }
  public ByteBuffer profileSidebarFillColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 66, 1); }
  public String profileTextColor() { int o = __offset(68); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer profileTextColorAsByteBuffer() { return __vector_as_bytebuffer(68, 1); }
  public ByteBuffer profileTextColorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 68, 1); }
  public boolean profileUseBackgroundImage() { int o = __offset(70); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateProfileUseBackgroundImage(boolean profile_use_background_image) { int o = __offset(70); if (o != 0) { bb.put(o + bb_pos, (byte)(profile_use_background_image ? 1 : 0)); return true; } else { return false; } }
  public int utcOffset() { int o = __offset(72); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateUtcOffset(int utc_offset) { int o = __offset(72); if (o != 0) { bb.putInt(o + bb_pos, utc_offset); return true; } else { return false; } }
  public String timeZone() { int o = __offset(74); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer timeZoneAsByteBuffer() { return __vector_as_bytebuffer(74, 1); }
  public ByteBuffer timeZoneInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 74, 1); }
  public boolean isTranslator() { int o = __offset(76); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateIsTranslator(boolean is_translator) { int o = __offset(76); if (o != 0) { bb.put(o + bb_pos, (byte)(is_translator ? 1 : 0)); return true; } else { return false; } }
  public boolean followRequestSent() { int o = __offset(78); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateFollowRequestSent(boolean follow_request_sent) { int o = __offset(78); if (o != 0) { bb.put(o + bb_pos, (byte)(follow_request_sent ? 1 : 0)); return true; } else { return false; } }
  public boolean showAllInlineMedia() { int o = __offset(80); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateShowAllInlineMedia(boolean show_all_inline_media) { int o = __offset(80); if (o != 0) { bb.put(o + bb_pos, (byte)(show_all_inline_media ? 1 : 0)); return true; } else { return false; } }

  public static int createUserFBS(FlatBufferBuilder builder,
      long id,
      int idStrOffset,
      int nameOffset,
      int screenNameOffset,
      int locationOffset,
      int urlOffset,
      int descriptionOffset,
      boolean isProtected,
      boolean verified,
      int followersCount,
      int friendsCount,
      int listedCount,
      int favouritesCount,
      int statusesCount,
      int createdAtOffset,
      int profileBannerUrlOffset,
      int profileImageUrlHttpsOffset,
      boolean defaultProfile,
      int withheldInCountriesOffset,
      int withheldScopeOffset,
      int descriptionUrlEntitiesOffset,
      boolean geoEnabled,
      int langOffset,
      boolean contributorsEnabled,
      int profileBackgroundColorOffset,
      int profileBackgroundImageUrlOffset,
      int profileBackgroundImageUrlHttpsOffset,
      boolean profileBackgroundTile,
      int profileImageUrlOffset,
      int profileLinkColorOffset,
      int profileSidebarBorderColorOffset,
      int profileSidebarFillColorOffset,
      int profileTextColorOffset,
      boolean profileUseBackgroundImage,
      int utcOffset,
      int timeZoneOffset,
      boolean isTranslator,
      boolean followRequestSent,
      boolean showAllInlineMedia) {
    builder.startTable(39);
    UserFBS.addId(builder, id);
    UserFBS.addTimeZone(builder, timeZoneOffset);
    UserFBS.addUtcOffset(builder, utcOffset);
    UserFBS.addProfileTextColor(builder, profileTextColorOffset);
    UserFBS.addProfileSidebarFillColor(builder, profileSidebarFillColorOffset);
    UserFBS.addProfileSidebarBorderColor(builder, profileSidebarBorderColorOffset);
    UserFBS.addProfileLinkColor(builder, profileLinkColorOffset);
    UserFBS.addProfileImageUrl(builder, profileImageUrlOffset);
    UserFBS.addProfileBackgroundImageUrlHttps(builder, profileBackgroundImageUrlHttpsOffset);
    UserFBS.addProfileBackgroundImageUrl(builder, profileBackgroundImageUrlOffset);
    UserFBS.addProfileBackgroundColor(builder, profileBackgroundColorOffset);
    UserFBS.addLang(builder, langOffset);
    UserFBS.addDescriptionUrlEntities(builder, descriptionUrlEntitiesOffset);
    UserFBS.addWithheldScope(builder, withheldScopeOffset);
    UserFBS.addWithheldInCountries(builder, withheldInCountriesOffset);
    UserFBS.addProfileImageUrlHttps(builder, profileImageUrlHttpsOffset);
    UserFBS.addProfileBannerUrl(builder, profileBannerUrlOffset);
    UserFBS.addCreatedAt(builder, createdAtOffset);
    UserFBS.addStatusesCount(builder, statusesCount);
    UserFBS.addFavouritesCount(builder, favouritesCount);
    UserFBS.addListedCount(builder, listedCount);
    UserFBS.addFriendsCount(builder, friendsCount);
    UserFBS.addFollowersCount(builder, followersCount);
    UserFBS.addDescription(builder, descriptionOffset);
    UserFBS.addUrl(builder, urlOffset);
    UserFBS.addLocation(builder, locationOffset);
    UserFBS.addScreenName(builder, screenNameOffset);
    UserFBS.addName(builder, nameOffset);
    UserFBS.addIdStr(builder, idStrOffset);
    UserFBS.addShowAllInlineMedia(builder, showAllInlineMedia);
    UserFBS.addFollowRequestSent(builder, followRequestSent);
    UserFBS.addIsTranslator(builder, isTranslator);
    UserFBS.addProfileUseBackgroundImage(builder, profileUseBackgroundImage);
    UserFBS.addProfileBackgroundTile(builder, profileBackgroundTile);
    UserFBS.addContributorsEnabled(builder, contributorsEnabled);
    UserFBS.addGeoEnabled(builder, geoEnabled);
    UserFBS.addDefaultProfile(builder, defaultProfile);
    UserFBS.addVerified(builder, verified);
    UserFBS.addIsProtected(builder, isProtected);
    return UserFBS.endUserFBS(builder);
  }

  public static void startUserFBS(FlatBufferBuilder builder) { builder.startTable(39); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addIdStr(FlatBufferBuilder builder, int idStrOffset) { builder.addOffset(1, idStrOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static void addScreenName(FlatBufferBuilder builder, int screenNameOffset) { builder.addOffset(3, screenNameOffset, 0); }
  public static void addLocation(FlatBufferBuilder builder, int locationOffset) { builder.addOffset(4, locationOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(5, urlOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(6, descriptionOffset, 0); }
  public static void addIsProtected(FlatBufferBuilder builder, boolean isProtected) { builder.addBoolean(7, isProtected, false); }
  public static void addVerified(FlatBufferBuilder builder, boolean verified) { builder.addBoolean(8, verified, false); }
  public static void addFollowersCount(FlatBufferBuilder builder, int followersCount) { builder.addInt(9, followersCount, 0); }
  public static void addFriendsCount(FlatBufferBuilder builder, int friendsCount) { builder.addInt(10, friendsCount, 0); }
  public static void addListedCount(FlatBufferBuilder builder, int listedCount) { builder.addInt(11, listedCount, 0); }
  public static void addFavouritesCount(FlatBufferBuilder builder, int favouritesCount) { builder.addInt(12, favouritesCount, 0); }
  public static void addStatusesCount(FlatBufferBuilder builder, int statusesCount) { builder.addInt(13, statusesCount, 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, int createdAtOffset) { builder.addOffset(14, createdAtOffset, 0); }
  public static void addProfileBannerUrl(FlatBufferBuilder builder, int profileBannerUrlOffset) { builder.addOffset(15, profileBannerUrlOffset, 0); }
  public static void addProfileImageUrlHttps(FlatBufferBuilder builder, int profileImageUrlHttpsOffset) { builder.addOffset(16, profileImageUrlHttpsOffset, 0); }
  public static void addDefaultProfile(FlatBufferBuilder builder, boolean defaultProfile) { builder.addBoolean(17, defaultProfile, false); }
  public static void addWithheldInCountries(FlatBufferBuilder builder, int withheldInCountriesOffset) { builder.addOffset(18, withheldInCountriesOffset, 0); }
  public static int createWithheldInCountriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startWithheldInCountriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addWithheldScope(FlatBufferBuilder builder, int withheldScopeOffset) { builder.addOffset(19, withheldScopeOffset, 0); }
  public static void addDescriptionUrlEntities(FlatBufferBuilder builder, int descriptionUrlEntitiesOffset) { builder.addOffset(20, descriptionUrlEntitiesOffset, 0); }
  public static int createDescriptionUrlEntitiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDescriptionUrlEntitiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGeoEnabled(FlatBufferBuilder builder, boolean geoEnabled) { builder.addBoolean(21, geoEnabled, false); }
  public static void addLang(FlatBufferBuilder builder, int langOffset) { builder.addOffset(22, langOffset, 0); }
  public static void addContributorsEnabled(FlatBufferBuilder builder, boolean contributorsEnabled) { builder.addBoolean(23, contributorsEnabled, false); }
  public static void addProfileBackgroundColor(FlatBufferBuilder builder, int profileBackgroundColorOffset) { builder.addOffset(24, profileBackgroundColorOffset, 0); }
  public static void addProfileBackgroundImageUrl(FlatBufferBuilder builder, int profileBackgroundImageUrlOffset) { builder.addOffset(25, profileBackgroundImageUrlOffset, 0); }
  public static void addProfileBackgroundImageUrlHttps(FlatBufferBuilder builder, int profileBackgroundImageUrlHttpsOffset) { builder.addOffset(26, profileBackgroundImageUrlHttpsOffset, 0); }
  public static void addProfileBackgroundTile(FlatBufferBuilder builder, boolean profileBackgroundTile) { builder.addBoolean(27, profileBackgroundTile, false); }
  public static void addProfileImageUrl(FlatBufferBuilder builder, int profileImageUrlOffset) { builder.addOffset(28, profileImageUrlOffset, 0); }
  public static void addProfileLinkColor(FlatBufferBuilder builder, int profileLinkColorOffset) { builder.addOffset(29, profileLinkColorOffset, 0); }
  public static void addProfileSidebarBorderColor(FlatBufferBuilder builder, int profileSidebarBorderColorOffset) { builder.addOffset(30, profileSidebarBorderColorOffset, 0); }
  public static void addProfileSidebarFillColor(FlatBufferBuilder builder, int profileSidebarFillColorOffset) { builder.addOffset(31, profileSidebarFillColorOffset, 0); }
  public static void addProfileTextColor(FlatBufferBuilder builder, int profileTextColorOffset) { builder.addOffset(32, profileTextColorOffset, 0); }
  public static void addProfileUseBackgroundImage(FlatBufferBuilder builder, boolean profileUseBackgroundImage) { builder.addBoolean(33, profileUseBackgroundImage, false); }
  public static void addUtcOffset(FlatBufferBuilder builder, int utcOffset) { builder.addInt(34, utcOffset, 0); }
  public static void addTimeZone(FlatBufferBuilder builder, int timeZoneOffset) { builder.addOffset(35, timeZoneOffset, 0); }
  public static void addIsTranslator(FlatBufferBuilder builder, boolean isTranslator) { builder.addBoolean(36, isTranslator, false); }
  public static void addFollowRequestSent(FlatBufferBuilder builder, boolean followRequestSent) { builder.addBoolean(37, followRequestSent, false); }
  public static void addShowAllInlineMedia(FlatBufferBuilder builder, boolean showAllInlineMedia) { builder.addBoolean(38, showAllInlineMedia, false); }
  public static int endUserFBS(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishUserFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedUserFBSBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserFBS get(int j) { return get(new UserFBS(), j); }
    public UserFBS get(UserFBS obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

